INCLUDES += -I$(RIOTCPU)/msp430_common/include/

CFLAGS += -DCPU_MODEL_$(call uppercase_and_underscore,$(CPU_MODEL))

export USEMODULE += msp430_common msp430_common_periph periph_common

DEFAULT_MODULE += oneway_malloc

# include the msp430 common Makefile
include $(RIOTMAKE)/arch/msp430.inc.mk
