# define the cpu used by SAMR21 Xplained Pro board
export CPU = samd21
export CPU_MODEL = samr21g18a

# set edbg device type
EDBG_DEVICE_TYPE = atmel_cm0p

#
export ROM_SIZE = 0x40000
export SLOT0_SIZE = 0x2000
export SLOT1_SIZE = 0x19000
export SLOT2_SIZE = 0x19000

include $(RIOTMAKE)/boards/sam0.inc.mk
