ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
  USEMODULE += at86rf233
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter ztimer,$(USEMODULE)))
  USEMODULE += ztimer_rtt ztimer_convert ztimer_extend
endif
