ifneq (1,$(LAZE))
  APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))
  ifneq (,$(filter tests_driver_%,$(APPLICATION)))
    BOARD ?= samr21-xpro
  endif
else
  APPLICATION ?= $(notdir $(patsubst %/,%,$(CURDIR)))
  ifneq (,$(filter driver_%,$(APPLICATION)))
    BOARD ?= samr21-xpro
  endif
endif

ifneq (,$(wildcard $(CURDIR)/tests/.))
  DEFAULT_MODULE += test_utils_interactive_sync
endif

BOARD ?= native
RIOTBASE ?= $(CURDIR)/../..
QUIET ?= 1
# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1
