ifneq (1,$(LAZE))
  APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))
else
  APPLICATION ?= $(notdir $(patsubst %/,%,$(CURDIR)))
endif
ifneq (,$(filter tests_driver_%,$(APPLICATION)))
    BOARD ?= samr21-xpro
endif
BOARD ?= native
RIOTBASE ?= $(CURDIR)/../..
QUIET ?= 1
# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1
