USEMODULE += lvgl
USEMODULE += lvgl_core
USEMODULE += lvgl_draw
USEMODULE += lvgl_font
USEMODULE += lvgl_extra
USEMODULE += lvgl_hal
USEMODULE += lvgl_misc
USEMODULE += lvgl_widgets

USEMODULE += lvgl_extra_layout_flex
USEMODULE += lvgl_extra_layout_grid

USEMODULE += lvgl_extra_theme_basic
USEMODULE += lvgl_extra_theme_default
USEMODULE += lvgl_extra_theme_mono

USEMODULE += lvgl_extra_widget_animimg
USEMODULE += lvgl_extra_widget_calendar
USEMODULE += lvgl_extra_widget_chart
USEMODULE += lvgl_extra_widget_colorwheel
USEMODULE += lvgl_extra_widget_imgbtn
USEMODULE += lvgl_extra_widget_keyboard
USEMODULE += lvgl_extra_widget_led
USEMODULE += lvgl_extra_widget_list
USEMODULE += lvgl_extra_widget_meter
USEMODULE += lvgl_extra_widget_msgbox
USEMODULE += lvgl_extra_widget_spinbox
USEMODULE += lvgl_extra_widget_spinner
USEMODULE += lvgl_extra_widget_tabview
USEMODULE += lvgl_extra_widget_tileview
USEMODULE += lvgl_extra_widget_win

ifneq (,$(filter lvgl_contrib,$(USEMODULE)))
  USEMODULE += disp_dev
  USEMODULE += core_thread_flags
  USEMODULE += ztimer
  USEMODULE += ztimer_msec
endif

ifneq (,$(filter lvgl_contrib_touch,$(USEMODULE)))
  USEMODULE += touch_dev
endif

# lvgl is not compatible with non 32bit platforms
# Building lv_misc triggers the error:
# "left shift count >= width of type [-Werror=shift-count-overflow]"
FEATURES_BLACKLIST += arch_8bit
FEATURES_BLACKLIST += arch_16bit
