USEMODULE += lvgl
USEMODULE += lvgl_core
USEMODULE += lvgl_draw
USEMODULE += lvgl_font
USEMODULE += lvgl_hal
USEMODULE += lvgl_misc
USEMODULE += lvgl_widgets

USEMODULE += lvgl_extra

USEMODULE += lvgl_layout_flex
USEMODULE += lvgl_layout_grid

USEMODULE += lvgl_theme_basic
USEMODULE += lvgl_theme_default
USEMODULE += lvgl_theme_mono

USEMODULE += lvgl_widget_chart
USEMODULE += lvgl_widget_list
USEMODULE += lvgl_widget_spinbox
USEMODULE += lvgl_widget_tileview
USEMODULE += lvgl_widget_tabview
USEMODULE += lvgl_widget_win
USEMODULE += lvgl_widget_msgbox
USEMODULE += lvgl_widget_meter
USEMODULE += lvgl_widget_calendar
USEMODULE += lvgl_widget_list
USEMODULE += lvgl_widget_colorwheel
USEMODULE += lvgl_widget_led
USEMODULE += lvgl_widget_keyboard


ifneq (,$(filter lvgl_contrib,$(USEMODULE)))
  USEMODULE += disp_dev
  USEMODULE += core_thread_flags
  USEMODULE += ztimer
  USEMODULE += ztimer_msec
endif

ifneq (,$(filter lvgl_contrib_touch,$(USEMODULE)))
  USEMODULE += touch_dev
endif

# lvgl is not compatible with non 32bit platforms
# Building lv_misc triggers the error:
# "left shift count >= width of type [-Werror=shift-count-overflow]"
FEATURES_BLACKLIST += arch_8bit
FEATURES_BLACKLIST += arch_16bit
