include ../Makefile.tests_common

USEMODULE += core_sandbox cortexm_svc
USEMODULE += syscall xtimer
FEATURES_REQUIRED += cortexm_mpu
FEATURES_BLACKLIST += cortexm_fpu

include $(RIOTBASE)/Makefile.include
