# CPU used by this board
CPU = msp430fr59xx
CPU_MODEL = msp430fr5969

USEMODULE += stdio_uart

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM1
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))
# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

FLASHFILE = $(HEXFILE)

# taken from chronos
export OFLAGS = -O ihex
export FLASHER = mspdebug
export FFLAGS = tilib "prog $(FLASHFILE)"
