# for this board, we are using Segger's RTT as default terminal interface,
# unless the application sets something else
ifeq (,$(filter stdio_%,$(USEMODULE)))
  USEMODULE += stdio_rtt
  TERMPROG = $(RIOTTOOLS)/jlink/jlink.sh
  TERMFLAGS = term_rtt
endif

# use shared Makefile.include
include $(RIOTBOARD)/common/nrf52xxxdk/Makefile.include
