APPLICATION = mutex_order
include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := stm32f0discovery weio nucleo-f030 nucleo32-f042

test:
	./tests/01-run.py

include $(RIOTBASE)/Makefile.include
