CFLAGS += -Wno-implicit-fallthrough
CFLAGS += -Wno-unused-parameter
CFLAGS += -Wno-sign-compare
CFLAGS += -Wno-old-style-definition
CFLAGS += -Wno-unused-function
CFLAGS += -Wno-unused-variable

include $(RIOTBASE)/Makefile.base
