PKG_NAME=doomgeneric
PKG_URL=https://github.com/ozkl/doomgeneric
PKG_VERSION=2d9b24f07c78c36becf41d89db30fa99863463e5
PKG_LICENSE=GPL-v2

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
