BOARD ?= samr21-xpro

include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-mega2560 arduino-nano \
                             arduino-uno chronos msb-430 msb-430h \
                             nucleo-f031k6 nucleo-f042k6 nucleo-l031k6 \
                             nucleo-f030r8 nucleo-f303k8 nucleo-l053r8 \
                             stm32f0discovery telosb waspmote-pro wsn430-v1_3b \
                             wsn430-v1_4 z1


# lower pktbuf size a little
CFLAGS += -DGNRC_PKTBUF_SIZE=2000

#
# Networking
#
# Include packages that pull up and auto-init the link layer.
# NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
# Specify the mandatory networking modules for IPv6 and UDP
USEMODULE += gnrc_ipv6_router_default
USEMODULE += gnrc_udp
USEMODULE += gnrc_sock_udp
# Additional networking modules that can be dropped if not needed
USEMODULE += gnrc_icmpv6_echo

# include this for printing IP addresses
USEMODULE += shell_commands

# Comment this out to enable code in RIOT that does safety checking
# which is not needed in a production environment but helps in the
# development process:
#DEVELHELP = 1

#
# SUIT update specific stuff
#

USEMODULE += nanocoap_sock sock_util
USEMODULE += suit suit_coap

# v4:
USEMODULE += suit_v4
INCLUDES += -I$(CURDIR) # Include public_key.h in the path


ifneq (native,$(BOARD))
  FEATURES_REQUIRED += riotboot
  USEMODULE += riotboot_slot riotboot_flashwrite riotboot_flashwrite_verify_sha256
endif

# The test script assumes initially version "0" is flashed,
# as done by the CI.
# Thus default to that (instead of epoch set by makefiles/boot/riotboot.inc.mk).
APP_VER?=0

# The test needs the linked slot binaries without header in order to be able to
# create final binaries with specific APP_VER values. The CI RasPi test workers
# don't compile themselves, thus add the required files here so they will be
# submitted along with the test jobs.
TEST_EXTRA_FILES=$(SLOT_RIOT_ELFS)

# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1

# Change this to 0 to not use ethos
USE_ETHOS ?= 1
TAP ?= tap0
IPV6_PREFIX ?= 2001:db8::/64

ifeq (1,$(USE_ETHOS))
ifeq (,$(filter native,$(BOARD)))
  GNRC_NETIF_NUMOF := 2
  USEMODULE += stdio_ethos
  USEMODULE += gnrc_uhcpc

  # ethos baudrate can be configured from make command
  ETHOS_BAUDRATE ?= 115200
  CFLAGS += -DETHOS_BAUDRATE=$(ETHOS_BAUDRATE)

  TERMDEPS += host-tools
  ifneq (1,$(RIOT_CI_BUILD))
    TERMPROG ?= sudo sh $(RIOTTOOLS)/ethos/start_network.sh
    TERMFLAGS ?= $(PORT) $(TAP) $(IPV6_PREFIX)
  else
    # The network is pre-configured on RIOT's CI workers
    export TAP=riot0
    IPV6_PREFIX=2001:db8::/64
    TERMPROG = $(RIOTTOOLS)/ethos/ethos
    TERMFLAGS = $(TAP) $(PORT)
  endif
endif
endif

# Use different settings when compiling for one of the following (low-memory)
# boards
LOW_MEMORY_BOARDS := nucleo-f334r8

ifneq (,$(filter $(BOARD),$(LOW_MEMORY_BOARDS)))
  $(info Using low-memory configuration for microcoap_server.)
  ## low-memory tuning values
  # lower pktbuf buffer size
  CFLAGS += -DGNRC_PKTBUF_SIZE=1000
  USEMODULE += prng_minstd
endif

include $(RIOTBASE)/Makefile.include

.PHONY: host-tools

host-tools:
	$(Q)env -u CC -u CFLAGS make -C $(RIOTTOOLS)

# Set a custom channel if needed
ifneq (,$(filter cc110x,$(USEMODULE)))          # radio is cc110x sub-GHz
  DEFAULT_CHANNEL ?= 0
  CFLAGS += -DCC110X_DEFAULT_CHANNEL=$(DEFAULT_CHANNEL)
else
  ifneq (,$(filter at86rf212b,$(USEMODULE)))    # radio is IEEE 802.15.4 sub-GHz
    DEFAULT_CHANNEL ?= 5
    CFLAGS += -DIEEE802154_DEFAULT_SUBGHZ_CHANNEL=$(DEFAULT_CHANNEL)
  else                                          # radio is IEEE 802.15.4 2.4 GHz
    DEFAULT_CHANNEL ?= 26
    CFLAGS += -DIEEE802154_DEFAULT_CHANNEL=$(DEFAULT_CHANNEL)
  endif
endif
