USEPKG += lvgl

ifneq (,$(filter lv_drivers_display_sdl,$(USEMODULE)))
  FEATURES_REQUIRED += arch_native
  USEMODULE += lv_drivers_sdl
endif

ifneq (,$(filter lv_drivers_indev_mouse,$(USEMODULE)))
  FEATURES_REQUIRED += arch_native
  USEMODULE += lv_drivers_mouse
endif
