USEPKG += lvgl

ifneq (,$(filter lv_drivers_display_monitor,$(USEMODULE)))
  FEATURES_REQUIRED += arch_native
endif

ifneq (,$(filter lv_drivers_indev_mouse,$(USEMODULE)))
  FEATURES_REQUIRED += arch_native
endif

